### ISSUE TITLE
Request card's title is not readable on mobile

### ISSUE THREAD

**Issue by larxn** [veganhacktivists/veganhacktivists#122]
## Problem
Request card's title is not readable on mobile. Could we remove `line-clamp-1` from this [line](https://github.com/veganhacktivists/veganhacktivists/blob/55dc988b35815c24bb7cc225a55539278032dc42/src/components/layout/playground/requests/requestCard.tsx#L92)? Or is there a reason why we need it there? I think the yellow stripe doesn't look bad with that height (but that's just an opinion 😁) .

I tested this with my browser's Inspector and it would look like the picture on the right.

## Screenshot

![image](https://user-images.githubusercontent.com/16514302/188031383-d3d92bc7-1f85-45e3-b2e2-3fad9a43f9f1.png)

**Comment by JoaquinTrinanes** [comment]
@luvejo good call! For some reason I assumed that the title was one line and just kept adding the clamp. I added some sensible limits in #126 but the title should fully appear for most requests, and always in the request page itself.
