### ISSUE TITLE
Portfolio website is required even if it doesn't make sense

### ISSUE THREAD

**Issue by braaar** [veganhacktivists/veganhacktivists#185]
![Screenshot 2022-11-15 at 15 00 42](https://user-images.githubusercontent.com/5765650/201925853-baa03522-45ae-4db0-a949-3b7ca7fb12f7.jpg)

It seems unreasonable that a portfolio website is required for simple requests such as [this request for mini-activism ideas](https://veganhacktivists.org/playground/request/clai6de730001c702jwuwqtpy).

**Comment by MatsThieme** [comment]
This portfolio website could be a link to any references of yours, such as LinkedIn, Github or a personal website.
