### ISSUE TITLE
create walkthrough videos for repo's

### ISSUE THREAD

**Issue by BrittanyBunk** [veganhacktivists/veganhacktivists#269]
The repo's can be a little difficult to follow or maybe people wouldn't want to read all of it, or need some video to follow along for instructions and steps. I feel walkthrough videos - if posted on a youtube channel - and embedded within the readme's - could significantly improve access to the tools these repo's provide - for what personal vegan projects need for self-sufficient success.

**Comment by MatsThieme** [comment]
Hi, this repo hosts only the veganhacktivists.org codebase. If you think this or another repo is lacking documentation, please create an issue or pull request there.
