### ISSUE TITLE
Broken link in repository description

### ISSUE THREAD

**Issue by braaar** [veganhacktivists/veganhacktivists#52]
The link in the sidebar of this repository sends me to https://github.com/veganhacktivists.org/. There seems to be a `/` missing from `https://`:

```
About
The veganhacktivists.org website, built using Next.js and hosted on our Digital Ocean Docker droplet

https:/veganhacktivists.org/
```

**Comment by JoaquinTrinanes** [comment]
You're right @braaar, we just fixed it!

Thank you so much for the heads up :chicken::green_heart:
