### ISSUE TITLE
Flickering in animation on "See all posts" button

### ISSUE THREAD

**Issue by braaar** [veganhacktivists/veganhacktivists#53]
https://user-images.githubusercontent.com/5765650/137633253-14e19981-5e16-49d5-9ddc-95aa3f63d16d.mov

This issue also occurs on the "Meet the team" button, the leftmost "See more" button and the "Apply now!" button on the bottom of the front page.

It seems almost like the issue only occurs on the first button within a component or something?

**My system** 
Google Chrome Version 94.0.4606.81 (Official Build) (x86_64)
MacOS Big Sur 11.06

**Comment by braaar** [comment]
I'm getting the same issue on every button on the projects page: https://veganhacktivists.org/projects

**Comment by braaar** [comment]
The "See more" buttons in the sidebar on this blog post do not have the issue: https://veganhacktivists.org/blog/meet-the-vegan-hacktivists-suan-chin

**Comment by JoaquinTrinanes** [comment]
Hey @braaar thanks for the report!

Looks like it's a CSS issue that I only manage to replicate in Chrome. I opened a PR that changes the way the button background is changed, should be fixed soon! :smiley:
