### ISSUE TITLE
Typeform: Developer sign up form text is outdated

### ISSUE THREAD

**Issue by braaar** [veganhacktivists/veganhacktivists#55]
Not sure if this is actually a part of this repo, but I couldn't find any other relevant repositories. When reading through the sign up form for developers, I found this piece of text which references Trello being used for issue tracking, which I believe is no longer the case:

> We're looking for developers that have experience with PHP, JS and CSS. We use Laravel for all of our projects combined with Bootstrap. We use Github and Trello to work collaboratively, and we use Discord as our primary source of communication. It's okay if you're not 100% familiar with Laravel, as long as you're able to pick it up without too much trouble, we're happy to help to get you started!

https://veganhacktivists.typeform.com/to/Vnrv6N

**Comment by JoaquinTrinanes** [comment]
Closing as per https://github.com/veganhacktivists/veganhacktivists/issues/56#issuecomment-946857933
