### ISSUE TITLE
Trello references in readme.md

### ISSUE THREAD

**Issue by braaar** [veganhacktivists/veganhacktivists#56]
`We're using Next.js and Tailwind for that. In [this trello board](https://trello.com/b/7FMaTCuc/veganhacktivistsorg) you can find more stuff in the info column, for example, some of the images to be used, fonts, colors... On the board you can also access the `Things to do` cards. If you are doubting which card to pick first, talk to [Joaquín [TL] 🇪🇸](https://github.com/JoaquinTrinanes) and we'll take a look at the available ones or even create others, in order for you to get used to the project.`

```md
## Grab a card

Steps for working on a card from [our Trello board](https://trello.com/b/7FMaTCuc/veganhacktivistsorg):

- Grab a card from the `Things to do` column and drag it to the `In Progress` column
- Create a new branch `feature/my-new-feature` off the `main` branch
- Create a Pull Request when you're done
- Move the card to `PR Ready`
- Sit back and wait for approvals or comments!

Feel free to ask other team members to review Pull Requests.
```

I assume you guys might be working on some new routines for this tuff. Perhaps you are planning to start using project boards?

Regardless, the links and references to the now deleted Trello board should probably be deleted.

**Comment by JoaquinTrinanes** [comment]
Hey @braaar thanks for the opened issues so far!

We are starting to use Github for tracking issues and VH: Playground tasks.

However, we're still using Trello internally, and plan to keep using it in the foreseeable future AFAIK :grin: 

I'm closing #55 alongside this issue. Thanks for all your contributions! :smile::pig2:
